spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdatabase
    username: postgresuser
    password: securepassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
  port: 8080
#  error:
#    path: /contacts
#    whitelabel:
#      enabled: false